ruby:
  enabled: true
  config_file: .rubocop.yml
coffeescript:
  enabled: true
  config_file: coffeelint.json
javascript:
  enabled: true
  config_file: .javascript-style.json
scss:
  enabled: false
