PreCommit:
  RuboCop:
    enabled: false
    command: ['bundle', 'exec', 'rubocop']
    problem_on_unmodified_line:
  EsLint:
    enabled: true
    problem_on_unmodified_line: ignore
  CoffeeLint:
    enabled: true
    problem_on_unmodified_line: ignore
