AllCops:
  RunRailsCops: true
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'vendor/assets/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
Blocks:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
StringLiterals:
  Enabled: false
Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
Style/StringLiterals:
  Enabled: false
