footer: 'Morbi vulputate, nisl at lacinia ultrices, eros sapien condimentum dolor, sodales aliquam mauris sapien sit amet libero.'
intro: 'Duis condimentum eu massa porta lacinia. Sed ornare, eros ac fringilla convallis, lorem nulla scelerisque mi, a volutpat purus mi a urna. Etiam eu pellentesque ligula. Integer vestibulum euismod lacus, sed porttitor lectus egestas et.'
author:
  email: 'david@example.org'
  first_name: 'David'
  last_name: 'Cash'
  full_name: 'David Cash'
invitation:
  state: 'invited'
  due_in_days: 42
  decline_reason: 'This was obviously a fake invite, and I am not a real scientist.'
  reviewer_suggestions: 'A real scientist would be better suited to review this manuscript.'
invitee:
  email: 'invitee@example.org'
  first_name: 'Indiana'
  last_name: 'Invitedottir'
  full_name: 'Indiana Invitedottir'
  title: 'Doctor'
invitee_name_or_email: 'Indiana Invitedottir'
inviter:
  email: 'inviter@example.org'
  first_name: 'Ignatius'
  last_name: 'Invitorson'
  full_name: 'Ignatius Invitorson'
  title: 'Doctor'
journal:
  logo_url: 'https://www.plos.org/uploads/image/file/27230/sm_plos-logo-sm.png'
  name: 'PLOS'
  staff_email: 'staff@example.org'
manuscript:
  abstract: 'In dignissim mauris nec blandit fermentum. Curabitur at maximus velit, sed malesuada lorem. Morbi egestas consectetur magna, vitae viverra lectus volutpat ut. Mauris sit amet velit at felis ullamcorper dictum in et felis. Phasellus convallis lobortis enim, eget fringilla nisl efficitur non. Aliquam erat volutpat. Duis iaculis tincidunt neque, quis scelerisque risus laoreet eget. Morbi lacus tellus, viverra nec viverra nec, molestie non enim. Fusce tincidunt felis dictum luctus feugiat. Sed condimentum justo massa, quis pellentesque sem rhoncus eget. Nullam pulvinar malesuada nisi, sed vulputate sapien tristique id.'
  academic_editors:
    -  email: 'academic@example.org'
       first_name: 'Academic'
       last_name: 'Editor'
       full_name: 'Academic Editor'
  authors:
    -   affiliation: 'ABC University'
        author_initial: 'J'
        email: 'john.doe@example.org'
        first_name: 'John'
        last_name: 'Doe'
        full_name: 'John Doe'
  corresponding_authors:
    -  affiliation: 'XYZ University'
       author_initial: 'J'
       email: 'jerry@example.org'
       first_name: 'Jerry'
       last_name: 'Moreland'
       full_name: 'Jerry Moreland'
  creator:
    email: 'marguerite@example.org'
    first_name: 'Marguerite'
    last_name: 'Wells'
    full_name: 'Marguerite Wells'
  editor:
    email: 'luisa@example.org'
    first_name: 'Luisa'
    last_name: 'Wolfe'
    full_name: 'Luisa Wolfe'
    title: 'Doctor'
  handling_editors:
    -  email: 'terri@example.org'
       first_name: 'Terri'
       last_name: 'Varela'
       full_name: 'Terri Varela'
  paper_type: 'Research'
  title: 'The Circadian Clock, the Cell Cycle and Cancer'
  url:  'http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.2002940'
reviewer:
  first_name: 'Henry'
  last_name: 'Slowik'
  full_name: 'Henry Slowik'
review: &review
  datetime: 'Sat, 03 Feb 2001 04:05:06 +0000'
  due_at: '2018-11-11'
  invitation_accepted?: 'true'
  rendered_answer_idents: '--ident'
  email: 'veronica@example.org'
  first_name: 'Veronica'
  last_name: 'Roland'
  full_name: 'Veronica Roland'
  reviewer_name: 'Veronica'
  reviewer_number: '854741'
  revision: '1'
  state: 'draft'
  status: 'completed'
  rendered_answers:
  -  ident: 'publishing_related_questions--published_elsewhere--taken_from_manuscripts'
     question: 'Results, data or figures'
     string_value: 'Check out figure 5"'
     value: 'Check out figure 5"'
     value_type: 'html'
reviews:
  -  <<: *review
sendback_reasons:
  - ident: '--fake-ident'
    question: 'Does the abstract have at least 100 words?'
    string_value: 'Your abstract only have 88 words'
    value: 'Your abstract only have 88 words'
    value_type: 'text'
paperwide_sendback_reasons: 'paperwide sendback reasons'
