journal:
  logo_url: 'https://www.plos.org/uploads/image/file/27230/sm_plos-logo-sm.png'
  name: 'PLOS'
  staff_email: 'staff@plos.org'
manuscript:
  abstract: 'Lorem Ipsum'
  academic_editors:
    -  email: 'academic@plos.org'
       first_name: 'Academic'
       last_name: 'Editor'
       full_name: 'Academic Editor'
  authors:
    -   affiliation: 'ABC University'
        author_initial: 'J'
        email: 'john.doe@plos.org'
        first_name: 'John'
        last_name: 'Doe'
  corresponding_authors:
    -  affiliation: 'XYZ University'
       author_initial: 'J'
       email: 'jerry@plos.org'
       first_name: 'Jerry'
       last_name: 'Moreland'
  creator:
    email: 'marguerite@plos.org'
    first_name: 'Marguerite'
    last_name: 'Wells'
    full_name: 'Marguerite Wells'
  editor:
    email: 'luisa@plos.org'
    first_name: 'Luisa'
    last_name: 'Wolfe'
    full_name: 'Luisa Wolfe'
    title: 'Doctor'
  handling_editors:
    -  email: 'terri@plos.org'
       first_name: 'Terri'
       last_name: 'Varela'
       full_name: 'Terri Varela'
  paper_type: 'Research'
  title: 'The Circadian Clock, the Cell Cycle and Cancer'
  url:  'http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.2002940'
reviews:
  - datetime: 'Sat, 03 Feb 2001 04:05:06 +0000'
    due_at: '2018-11-11 11:11:11'
    invitation_accepted?: 'true'
    rendered_answer_idents: '--ident'
    email: 'veronica@plos.org'
    first_name: 'Veronica'
    last_name: 'Roland'
    full_name: 'Veronica Roland'
    reviewer_name: 'Veronica'
    reviewer_number: '854741'
    revision: '1'
    state: 'draft'
    status: 'completed'
    rendered_answers:
    -  ident: 'publishing_related_questions--published_elsewhere--taken_from_manuscripts'
       question: 'Results, data or figures'
       string_value: 'Check out figure 5"'
       value: 'Check out figure 5"'
       value_type: 'html'
