require 'rails_helper'

# rubocop:disable Metrics/BlockLength
describe PaperConverters::AutoGeneratedDocxToPdfConverter do
  let(:export_format) { 'pdf' }
  let(:journal) do
    FactoryGirl.create(
      :journal,
      :with_creator_role,
      pdf_css: 'body { background-color: red; }'
    )
  end
  let(:user) { FactoryGirl.create :user }
  let(:paper) { create(:paper, :version_with_file_type, :with_creator, journal: journal) }
  let(:versioned_text) { paper.latest_version }
  let(:task) { FactoryGirl.create(:supporting_information_task) }
  let(:converter) { PaperConverters::AutoGeneratedDocxToPdfConverter.new(versioned_text, export_format, user) }

  it_behaves_like "a synchronous paper converter"

  describe "#output_filename" do
    subject { converter.output_filename }
    it { is_expected.to eq "aperta-generated-PDF.pdf" }
  end

  describe "#output_filetype" do
    subject { converter.output_filetype }
    it { is_expected.to eq('application/pdf') }
  end

  describe '#output_data' do
    it 'uses PDFKit to generate PDF' do
      expect(PDFKit).to receive_message_chain(:new, :to_pdf)
      converter.output_data { is_expected.to be_present }
    end
  end

  describe "#supporting_information_files" do
    subject { converter.supporting_information_files }

    it { is_expected.to eq [] }
  end
end
