require 'rails_helper'

describe PaperConverters::AutoGeneratedPdfToPdfConverter do
  let(:export_format) { 'pdf' }
  let(:paper) { create(:paper, :version_with_file_type, :with_creator) }
  let(:figure_count) { 2 }
  let!(:figures) { create_list(:figure, figure_count, owner: paper).tap { paper.reload } }
  let(:versioned_text) { paper.latest_version }
  let(:converter) { PaperConverters::AutoGeneratedPdfToPdfConverter.new(versioned_text, export_format) }
  let(:pdf_data) { File.read(Rails.root.join('spec/fixtures/about_turtles.pdf')) }

  it_behaves_like "a synchronous paper converter"

  describe "#output_filename" do
    subject { converter.output_filename }
    it { is_expected.to eq "aperta-generated-PDF.pdf" }
  end

  describe "#supporting_information_files" do
    subject { converter.supporting_information_files }

    it { is_expected.to eq [] }
  end

  describe "#output_data" do
    subject { converter.output_data }
    let(:sample_combine_pdf) { CombinePDF.parse pdf_data }

    before do
      allow(converter).to receive(:parsed_uploaded_pdf).and_return(sample_combine_pdf)
      allow(converter).to receive(:create_attachments_pdf).and_return(sample_combine_pdf)
    end

    it { is_expected.to be_present }
  end
end
