- name: add Wine repo
  apt_repository:
    repo: 'ppa:ubuntu-wine/ppa'

- name: add i386 architecture
  shell: sudo dpkg --add-architecture i386

- name: install Wine
  apt:
    pkg: wine1.7
    state: installed

- name: Configure Wine for the deploy user
  shell: WINEARCH=win32 winecfg
  args:
    creates: ~/.wine
  sudo_user: deploy

- name: install Xvfb
  apt:
    pkg: xvfb
    state: installed

- name: run Xvfb
  shell: Xvfb :1 -screen 0 800x600x16 -fbdir /var/tmp &
  sudo_user: deploy

- name: Get latest MathType
  get_url:
    url="{{ MATHTYPE_URL }}"
    dest="/tmp/mathtype.zip"
  sudo_user: deploy

- name: Unzip MathType
  shell: cd /tmp && unzip mathtype.zip
  args:
    creates: /tmp/InstallMTW6.9a
  sudo_user: deploy

- name: Install MathType
  shell: cd /tmp/InstallMTW6.9a && DISPLAY=:1 wine setup.exe -Q -I -DL "C:\Program Files\MathType"
  args:
    creates: ~/.wine/drive_c/Program Files/MathType
  sudo_user: deploy


- name: Get latest MathTypeToMathML converter
  get_url:
    url="{{ MATHTYPE_TO_MATHML_URL }}"
    dest=/tmp/converter.zip
  sudo_user: deploy

- name: Unzip MathTypeToMathML converter
  shell: cd /tmp && unzip converter.zip
  args:
    creates: /tmp/ConvertMathTypeToMathML
  sudo_user: deploy

- name: Create a directory in Wine for the converter
  shell: mkdir ~/.wine/drive_c/ConvertMathTypeToMathML
  args:
    creates: ~/.wine/drive_c/ConvertMathTypeToMathML
  sudo_user: deploy

- name: Install MathTypeToMathML converter
  shell: cd /tmp/ConvertMathTypeToMathML && cp -R * ~/.wine/drive_c/ConvertMathTypeToMathML/
  args:
    creates: ~/.wine/drive_c/ConvertMathTypeToMathML/ConvertMathTypeToMathML.exe
  sudo_user: deploy

- name: Install .NET 2.0
  shell: DISPLAY=:1 winetricks --unattended dotnet20
  sudo_user: deploy

- name: Test converter
  shell: cd ~/.wine/drive_c/ConvertMathTypeToMathML && DISPLAY=:1 wine ConvertMathTypeToMathML.exe
  register: converter
  sudo_user: deploy

- debug: var=converter

- name: Clean input directory of ConvertMathTypeToMathML
  file: path=~/.wine/drive_c/ConvertMathTypeToMathML/Input/input.bin state=absent
  sudo_user: deploy

- name: Clean output directory of ConvertMathTypeToMathML
  file: path=~/.wine/drive_c/ConvertMathTypeToMathML/Output/Output0.txt state=absent
  sudo_user: deploy
