 # This will be replaced by a .deb package in the future
- name: Install npm
  shell: curl https://www.npmjs.com/install.sh | bash creates=/usr/bin/npm

- name: Get npm global temporary directory
  command: npm -g config get tmp
  register: nodejs_npm_tempdir
  changed_when: False

- name: Set npm global temporary directory to /tmp
  command: npm -g config set tmp /tmp
  when: nodejs_npm_tempdir.stdout != '/tmp'
