- name: add Mono key server
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

- name: add Mono repo
  apt_repository:
    repo: deb http://download.mono-project.com/repo/debian wheezy main

- name: add Mono package
  apt:
    pkg: mono-complete
    state: installed

- name: Clone OpenXML SDK repo
  git: repo=https://github.com/OfficeDev/Open-Xml-Sdk
       dest=~/openxml

- name: Compile OpenXML using Mono
  shell: cd ~/openxml && make -f Makefile-Linux-Mono build

- name: Clone RevisionAccepter repo
  git: repo=https://github.com/Tahi-project/revision_accepter
       dest=~/revision_accepter

- name: Copy built OpenXML Dll to RevisionAccepter
  shell: cd ~/revision_accepter && cp ../openxml/build/OpenXmlSdkLib/OpenXMLLib.dll .

- name: Build RevisionAccepter binary
  shell: cd ~/revision_accepter && mcs -r:OpenXMLLib.dll,WindowsBase.dll,System.Xml.Linq.dll RevisionAccepter.cs

- name: Copy binary to /usr/local/bin
  shell: cp ~/revision_accepter/RevisionAccepter.exe /usr/local/bin/

- name: Copy DLL to /usr/local/bin
  shell: cp ~/revision_accepter/OpenXMLLib.dll /usr/local/bin/

- name: Cleanup OpenXML
  file: path=~/openxml state=absent

- name: Cleanup Revision Accepter
  file: path=~/revision_accepter state=absent
