ETahi.FigureTaskAdapter= ETahi.TaskAdapter.extend()
ETahi.DataAvailabilityTaskAdapter= ETahi.TaskAdapter.extend()
ETahi.CompetingInterestsTaskAdapter= ETahi.TaskAdapter.extend()
ETahi.EthicsTaskAdapter = ETahi.TaskAdapter.extend()
ETahi.FinancialDisclosureTaskAdapter= ETahi.TaskAdapter.extend()
ETahi.TaxonTaskAdapter= ETahi.TaskAdapter.extend()
