default: &default
  ssl: false
  host: 'localhost'
  login_url: '/cas/login'
  service_validate_url: '/cas/serviceValidate'

development:
  <<: *default
  port: '8080'

staging:
  <<: *default
  ssl: true
  host: 'register.plos.org'

test:
  <<: *default
  port: '8080'
