---
whitelist:
- MIT
- Apache 2.0
- ISC
- BSD
- 2-clause BSDL
- New BSD
- Ruby
- LGPL
- GPLv2
- GPLv2+
ignore_groups:
#- test
#- development
dependencies_file_dir: './doc/'
project_name: # project name
