module PaperConverters
  # In export Apex packages that contain generated PDF files,
  # the SI filenames of the generated PDF no longer link to downloadable files
  # The links still appear and function in PDFs downloaded from Aperta
  class AutoGeneratedSupportingInformationFileProxy <
                          SupportingInformationFileProxy
    def self.from_versioned_text(versioned_text)
      if versioned_text.latest_version?
        paper = versioned_text.paper
        return paper.supporting_information_files.map do |si_file|
          klass = AutoGeneratedSupportingInformationFileProxy
          klass.from_supporting_information_file(si_file)
        end
      else
        major_version = versioned_text.major_version
        minor_version = versioned_text.minor_version
        snapshots = versioned_text.paper.snapshots.supporting_information_files
                        .where(major_version: major_version,
                               minor_version: minor_version)
        return snapshots.map do |snapshot|
          AutoGeneratedSupportingInformationFileProxy.from_snapshot(snapshot)
        end
      end
    end

    def href(**params)
      ''
    end

    def preview?
      false
    end
  end
end
