module PaperConverters
  # PDF Converter used to convert added aperta generated PDF files
  class AutoGeneratedPdfToPdfConverter < PdfWithAttachmentsPaperConverter
    def output_filename
      "aperta-generated-PDF.pdf"
    end

    def supporting_information_files
      []
    end

    def output_data
      user_pdf = parsed_uploaded_pdf
    end
  end
end
