ETahi.FigureTaskSerializer = ETahi.TaskSerializer.extend()
ETahi.DataAvailabilityTaskSerializer = ETahi.TaskSerializer.extend()
ETahi.CompetingInterestsTaskSerializer = ETahi.TaskSerializer.extend()
ETahi.EthicsTaskSerializer = ETahi.TaskSerializer.extend()
ETahi.FinancialDisclosureTaskSerializer = ETahi.TaskSerializer.extend()
