#
# Tracks similarity check requests to iThenticate. ithenticate_id is the id
# generated by iThenticate for the similarity check request. We query their
# API by this number to see if the report has completed yet.
#
class CreateSimilarityChecks < ActiveRecord::Migration
  def change
    create_table :tahi_standard_tasks_similarity_checks do |t|
      t.integer :ithenticate_id
      t.integer :match_percent
      t.references :versioned_text, foreign_key: true, null: false
      t.string :report_link
      t.string :state, null: false
      t.timestamps null: false
    end
  end
end
