# Copyright (c) 2018 Public Library of Science

# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

#
# Tracks similarity check requests to iThenticate. ithenticate_id is the id
# generated by iThenticate for the similarity check request. We query their
# API by this number to see if the report has completed yet.
#
class CreateSimilarityChecks < ActiveRecord::Migration
  def change
    create_table :similarity_checks do |t|
      t.integer :ithenticate_document_id
      t.datetime :ithenticate_report_completed_at
      t.datetime :timeout_at
      t.string :document_s3_url
      t.integer :ithenticate_report_id
      t.integer :ithenticate_score
      t.references :versioned_text, foreign_key: true, null: false
      t.string :state, null: false
      t.timestamps null: false
    end
  end
end
