#
# Tracks similarity check requests to iThenticate. ithenticate_id is the id
# generated by iThenticate for the similarity check request. We query their
# API by this number to see if the report has completed yet.
#
class CreateTahiStandardTasksSimilarityChecks < ActiveRecord::Migration
  def change
    create_table :tahi_standard_tasks_similarity_checks do |t|
      t.integer :ithenticate_id
      t.integer :paper_id
      t.integer :task_id
      t.integer :user_id
      t.integer :match_percent
      t.string :state
      t.string :report_link
      t.string :error_message
      t.timestamps
    end
  end
end
