class UpdateUploadManuscriptCardAndTasksToMswordOptional < ActiveRecord::Migration
  def change
    Card.where(name: 'Upload Manuscript').each do |c|
      c.update!(xml: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<card required-for-submission=\"true\" workflow-display-only=\"false\">\n  <DisplayChildren>\n    <If condition=\"taskStateToggleable\">\n      <DisplayChildren>\n        <Description>\n          <text><p>\n            You can upload a replacement manuscript file at any time before you submit.\n            </p></text>\n        </Description>\n        <Description>\n          <text><p>\n            <b>PDF format:</b> For authors uploading a PDF manuscript file, figures and any SI information can be included in the manuscript and are not required separately for initial assessment.\n            If a revision is invited, separate figure and SI file upload will be required.\n            If preferred, you may upload those files separately before completing your submission.\n            </p></text>\n        </Description>\n        <If condition=\"mswordAllowed\">\n          <Description>\n            <text><p>\n              <b>Microsoft Word format:</b> Manuscripts uploaded in this format can take advantage of automatic\n              inline figure placement and visual version comparison features.\n              </p></text>\n          </Description>\n        </If>\n        <If condition=\"mswordAllowed\">\n          <FileUploader value-type=\"manuscript\" error-message=\"Please upload a Microsoft Word File (.docx or .doc) or PDF\">\n            <label>Upload Manuscript</label>\n            <possible-value label=\"doc\" value=\".doc\"/>\n            <possible-value label=\"docx\" value=\".docx\"/>\n            <possible-value label=\"pdf\" value=\".pdf\"/>\n          </FileUploader>\n          <FileUploader value-type=\"manuscript\" error-message=\"Please upload a PDF file\">\n            <label>Upload Manuscript</label>\n            <possible-value label=\"pdf\" value=\".pdf\"/>\n          </FileUploader>\n        </If>\n      </DisplayChildren>\n      <Description>\n        <text>You are unable to upload a new manuscript while your submission is under review</text>\n      </Description>\n    </If>\n    <If condition=\"needsSourcefile\">\n      <DisplayChildren>\n        <Description>\n          <text><h4>Please Upload Your Source File</h4>\n                <span>Because you uploaded a PDF, you must also provide your source file (e.g. .tex, .docx) before marking this task as done.</span></text>\n        </Description>\n        <FileUploader value-type=\"sourcefile\">\n          <possible-value label=\"doc\" value=\".doc\"/>\n          <possible-value label=\"docx\" value=\".docx\"/>\n          <possible-value label=\"tex\" value=\".tex\"/>\n          <possible-value label=\"zip\" value=\".zip\"/>\n        </FileUploader>\n        <ErrorMessage key=\"validationErrors.sourcefile\">\n          <text>Please upload your source file</text>\n        </ErrorMessage>\n      </DisplayChildren>\n    </If>\n  </DisplayChildren>\n</card>\n")
      c.publish! 'msword optional'

      latest_version_id = c.latest_published_card_version.id
      Task.joins(:card_version).where(card_versions: { card_id: c.id }).each do |t|
        t.update_attributes!(card_version_id: latest_version_id)
      end
    end
  end
end
