- hosts: all
  gather_facts: true
  remote_user: root

- hosts: webservers
  sudo: yes
  remote_user: ubuntu
  vars_files:
    - vars/common.yml
  handlers:
    - include: roles/nginx/handlers/main.yml
  roles:
    - base
    - {role: ssh, when: vagrant is not defined}
    - {role: iptables, when: vagrant is not defined}
    - {role: nginx, when: vagrant is not defined}
    - redis
    - ruby
    - role: nodesource.node
      nodejs_version: "0.12"
      nodejs_nodesource_pin_priority: 500
    - npm

  tasks:
    - name: copy nginx
      template:
        src: templates/site-nginx.conf.j2
        dest: /etc/nginx/conf.d/sites.conf
      notify:
        - restart nginx

    - name: create directory for web sites
      file:
        state: directory
        path: /var/www
        owner: deploy
        group: deploy
        mode: 0755

    - name: copy tahi-project cert
      copy:
        src: files/{{ssl_cert_file}}
        dest: /etc/ssl/certs/{{ssl_cert_file}}

    - name: copy tahi-project key
      copy:
        src: files/{{ssl_key_file}}
        dest: /etc/ssl/private/{{ssl_key_file}}
